{% set version = "0.2.3" %}
{% set name = "pywin32-ctypes" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d162dc04946d704503b2edc4d55f3dba5c1d539ead017afa00142c38b9885755

build:
  number: 0
  skip: true  # [not win or py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

# E           win32ctypes.pywin32.pywintypes.error: (1168, 'CredEnumerate', 'Element not found.')
{% set deselect_tests = " --deselect=test_win32cred.py::TestCred::test_enumerate_all" %}

test:
  imports:
    - win32ctypes
  requires:
    - pip
    - pytest
    - pywin32
  commands:
    - pip check
    - pytest --pyargs win32ctypes.tests {{ deselect_tests }}

about:
  home: https://github.com/enthought/pywin32-ctypes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A limited subset of pywin32 re-implemented using ctypes (or cffi)
  description: |
    A reimplementation of pywin32 that is pure python. The default behaviour
    will try to use cffi (>= 1.3.0), if available, and fall back to using ctypes.
  doc_url: https://pywin32-ctypes.readthedocs.io
  dev_url: https://github.com/enthought/pywin32-ctypes

extra:
  recipe-maintainers:
    - ccordoba12
