travis:
  secure:
    BINSTAR_TOKEN: V+80njGy+OkXQHATfy2J/Niusj0MFqtqA7WVxP/PwiFqIts8LVBNZRCVavMzPCsKTE6dYqZMtGJYJck5FGU05fFRMjOcK1YWCdaHz5xGp2q25VIDsIAaVEIIOO1R897ep3ja2eX9EBzs2MQaOKrMtm3oiIOJ6S/5SbHSLup3QD4YMEpBeMxS4cZZ7LSX9IlLWiq49b9zdC6ifmUCh70qs2hRiPvpRrRbqXbR7BipjdcepuVAaAguFOKTHqmaZfz3cvuFQyTZMNIH7MD2EEXfMFdZ4YiU1hLQ1gVvxol1LKIx3A9IcXE6gTda89Y5IPiY2H3zi9TGLCWNwU68hRyqKrIcBiDsKgwOUATmilFlKo1QtOT13TbKQEu90JaVY76YrdTL1B5y4qmjJE+8jric93cnnj3Y7VmKWVPrSP+QVpWRBdTKIao/97N38hgj0a35u9FGaK597VlNbdWJQFTF62Z0eu44fx02jZSt3b4xDA7zEll83Roj5k7G/fOg1gYmL5dNgtHTimUVBhD7IymB7iD+fS9SOmK5xULltEQ/RdPh9/wKpGxU4TjlZoNJqtkCO8WfeFdv7iMHM8lhXT5qFACngRX/zRhoyO/ri1LZ+Y6E1NHy14RC9efXw6vICYHOlhNKniM9FJXY1eAkvIdbshEgwtuzvk9dCKpT0BDMgdU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
